#!/usr/bin/bash
if test "Excalibur" = $HOSTNAME ; then
   mount-SR
   mount-KE
   mount-CA
elif test "Square-Rigger" = $HOSTNAME ; then
   mount-EX
   mount-KE
   mount-CA
elif test "Catalina" = $HOSTNAME ; then
   mount-EX
   mount-SR
   mount-KE
elif test "Ketch" = $HOSTNAME ; then
   echo "Error in connet: Ketch doesn't use cifs mounts."
else
   echo "Error in connet: Unknown computer."
fi
