#!/usr/bin/bash
if test "Excalibur" = $HOSTNAME ; then
   umount-SR
   umount-KE
   umount-CA
elif test "Square-Rigger" = $HOSTNAME ; then
   umount-EX
   umount-KE
   umount-CA
elif test "Catalina" = $HOSTNAME ; then
   umount-EX
   umount-SR
   umount-KE
elif test "Ketch" = $HOSTNAME ; then
   echo "Error in disnet: Ketch doesn't use cifs mounts."
else
   echo "Error in disnet: Unknown computer."
fi
