#!/usr/bin/bash
sudo mount /home/aragorn/net/KE/Windows
sudo mount /home/aragorn/net/KE/Valinor
sudo mount /home/aragorn/net/KE/Beleriand
sudo mount /home/aragorn/net/KE/Eriador
sudo mount /home/aragorn/net/KE/Ossiriand
