#!/usr/bin/bash
sudo mount  /home/aragorn/net/SR/Rhudaur
sudo mount  /home/aragorn/net/SR/Rhovanion
sudo mount  /home/aragorn/net/SR/Imladris
sudo mount  /home/aragorn/net/SR/Lothlorien
sudo mount  /home/aragorn/net/SR/Gondor
sudo mount  /home/aragorn/net/SR/Amroth
