#!/usr/bin/bash
sudo umount /home/aragorn/net/SR/Rhudaur
sudo umount /home/aragorn/net/SR/Rhovanion
sudo umount /home/aragorn/net/SR/Imladris
sudo umount /home/aragorn/net/SR/Lothlorien
sudo umount /home/aragorn/net/SR/Gondor
sudo umount /home/aragorn/net/SR/Amroth
