#!/usr/bin/env -S perl -C63

# This is a 110-character-wide Unicode UTF-8 Perl-source-code text file with hard Unix line breaks ("\x0A").
# ¡Hablo Español! Говорю Русский. Björt skjöldur. ॐ नमो भगवते वासुदेवाय.    看的星星，知道你是爱。 麦藁雪、富士川町、山梨県。
# =======|=========|=========|=========|=========|=========|=========|=========|=========|=========|=========|

##############################################################################################################
# File name: "accent"
# Program description: adds diacritical marks to all bare vowels.
# Written by Robbie Hatley.
# Edit history:
# Sat Feb 15, 2025: Wrote it.
##############################################################################################################

use utf8;

while (<>) {
   tr/aeiouAEIOU/àéìóüÀÉÌÓÜ/;
   print;
}
