# Main Make File
# Note: Only automatically make frequenly-used categories.
# Don't automatically make humor, jive, libname, problematic, test, or Windows,
# as those require manual intervention.
.PHONY: a b
a : b
	$(MAKE) -C librh
	$(MAKE) -C fractals
	$(MAKE) -C games
	$(MAKE) -C geography
	$(MAKE) -C graphics
	$(MAKE) -C lore
	$(MAKE) -C math
	$(MAKE) -C util
